title: Making difference
author: Ati jian
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  this site talks about getting started with git  and blogging on it . it os a testing environment

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
